trigger:
- main

variables:
  azureSubscription: '2e8ea5df-06c8-40cc-97a1-4bd73594d716'
  webAppName: 'react-cicd-demo'

stages:
- stage: Build
  displayName: Build Vite React App
  jobs:
  - job: Build
    pool:
      name: my-pool
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        cd my-app
        npm install
        npm run build
      workingDirectory: '$(Build.SourcesDirectory)'
      displayName: 'Build Vite app'

    - script: |
        echo "=== Listing contents of $(Build.SourcesDirectory)\my-app ==="
        dir "$(Build.SourcesDirectory)\my-app"
        echo "=== Listing contents of dist folder (if exists) ==="
        dir "$(Build.SourcesDirectory)\my-app\dist"
      displayName: 'Check build output'
      continueOnError: true

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)\my-app\dist'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)\dist.zip'
        replaceExistingArchive: true
      displayName: 'Archive dist output'

    - publish: '$(Build.ArtifactStagingDirectory)\dist.zip'
      artifact: drop

- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: 'production'
    pool:
      name: my-pool
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              WebAppName: $(webAppName)
              packageForLinux: '$(Pipeline.Workspace)/drop/dist.zip'
              RuntimeStack: 'NODE|20-lts'
            displayName: 'Deploy Vite app to Azure App Service'
