trigger:
  - main

variables:
  azureSubscription: '2e8ea5df-06c8-40cc-97a1-4bd73594d716'
  webAppName: 'react-cicd-demo'
  nodeVersion: '20.x'

stages:
- stage: Build
  displayName: Build React App
  jobs:
  - job: Build
    pool:
      name: my-pool
    steps:
    - task: NodeTool@0
      displayName: Install Node.js
      inputs:
        versionSpec: '$(nodeVersion)'

    - script: |
        echo "DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)"
        echo "SourcesDirectory:       $(Build.SourcesDirectory)"
        echo "Pipeline.Workspace:     $(Pipeline.Workspace)"
        echo "Repo tree:"
        tree "$(System.DefaultWorkingDirectory)" /f /a || ls -laR "$(System.DefaultWorkingDirectory)"
        cd "$(System.DefaultWorkingDirectory)/my-app"
        npm ci
        npm run build
        echo "Built dist contents:"
        dir dist || ls -la dist
      displayName: Build Vite app

    - task: ArchiveFiles@2
      displayName: Archive dist output
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/my-app/dist'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/dist.zip'
      displayName: Publish artifact
      artifact: drop

- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: production
    pool:
      name: my-pool
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: Deploy React app to Azure App Service
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              WebAppName: $(webAppName)
              packageForLinux: '$(Pipeline.Workspace)/drop/dist.zip'
              RuntimeStack: 'NODE|20-lts'
